import {
  ClientIcon,
  DashIcon,
  ProfileIcon,
  ReportIcon,
  TeamIcon,
  WorkshopIcon,
  TransactionIcon,
  ProductIcon,
  MenuIcon,
  SettingIcon,
  SupportIcon,
} from "./components/icon";
export const cards = [
  {
    icon: "/Icons/user.svg",
    title: "Total Registered Users",
    figure: "6,124",
    img: "/Icons/arrow-up-right.svg",
    per: "100%",
  },
  {
    icon: "/Icons/Bag.svg",
    title: "Total Workshops Hosted",
    figure: "812",
    img: "/Icons/arrow-up-right.svg",
    per: "100%",
  },
  {
    icon: "/Icons/Document pdf.svg",
    title: "Total Products Published",
    figure: "2,139",
    img: "/Icons/arrow-up-right.svg",
    per: "100%",
  },
  {
    icon: "/Icons/Graduated.svg",
    title: "Total Workshops Hosted",
    figure: "318",
    img: "/Icons/arrow-up-right.svg",
    per: "100%",
  },
  {
    icon: "/Icons/Bank Card.svg",
    title: "Pending Payout Requests",
    figure: "21",
    img: "/Icons/arrow-up-right.svg",
    per: "100%",
  },
  {
    icon: "/Icons/Danger 3.svg",
    title: "Active Reports",
    figure: "6",
    img: "/Icons/arrow-up-right.svg",
    per: "100%",
  },
];
export const menuItems = [
  {
    icon: <DashIcon />,
    name: "Dashboard",
    to: "/home",
  },
  {
    icon: <ClientIcon />,
    name: "Clients & Experts",
    to: "/home/clients",
  },
  {
    icon: <TeamIcon />,
    name: "Teams",
    to: "/home/teams",
  },
  {
    icon: <WorkshopIcon />,
    name: "Workshops",
    to: "/home/workshops",
  },
  {
    icon: <ReportIcon />,
    name: "Reports & Reviews",
    to: "/home/reports",
  },
  {
    icon: <TransactionIcon />,
    name: "Transactions",
    to: "/home/transactions",
  },
  {
    icon: <ProductIcon />,
    name: "Product Management",
    to: "/home/product",
  },
  {
    icon: <MenuIcon />,
    name: "Menu Title",
    to: "/home/menu",
  },
];
export const menuSettings = [
  {
    icon: <SettingIcon />,
    name: "Settings",
    to: "/home/settings",
  },
  {
    icon: <SupportIcon />,
    name: "Support & Tickets",
    to: "/home/support",
  },
];

export const clientCards = [
  {
    icon: "/Icons/user.svg",
    title: "Total Clients",
    menu: "/Icons/Dropdown.svg",
    figure: "6,124",
    img: "/Icons/arrow-up-right.svg",
    per: "100%",
  },
  {
    icon: "/Icons/Add User.svg",
    title: "New Clients",
    menu: "/Icons/Dropdown.svg",
    figure: "316",
    img: "/Icons/arrow-up-right.svg",
    per: "100%",
  },
  {
    icon: "/Icons/Profile.svg",
    title: "Active Clients",
    menu: "/Icons/Dropdown.svg",
    figure: "2,420",
    img: "/Icons/Icon (2).svg",
    per: "100%",
  },
];
export const clients = [
  [
    {
      pic: "/Images/Avatar.svg",
      name: "Rhiannon Matthaias",
      email: "rhimat@com",
      bookingHistory: 23,
      date: "Oct 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Dain Aetos",
      email: "dainaetos@com",
      bookingHistory: 21,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Garrick Matthews",
      email: "garrick@com",
      bookingHistory: 25,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Mira Sorrengail",
      email: "mirasorren@com",
      bookingHistory: 13,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Ridoc Davis",
      email: "ridocdav@com",
      bookingHistory: 12,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Liam Mairi",
      email: "liammairi@com",
      bookingHistory: 5,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Violet Sorrengail",
      email: "violetdrier@com",
      bookingHistory: 10,
      date: "Sept 24, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
  ],
  [
    {
      pic: "/Images/Avatar.svg",
      name: "Rhiannon Matthaias",
      email: "rhimat@com",
      bookingHistory: 23,
      date: "Oct 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Dain Aetos",
      email: "dainaetos@com",
      bookingHistory: 21,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Garrick Matthews",
      email: "garrick@com",
      bookingHistory: 25,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Mira Sorrengail",
      email: "mirasorren@com",
      bookingHistory: 13,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Ridoc Davis",
      email: "ridocdav@com",
      bookingHistory: 12,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Liam Mairi",
      email: "liammairi@com",
      bookingHistory: 5,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Violet Sorrengail",
      email: "violetdrier@com",
      bookingHistory: 10,
      date: "Sept 24, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
  ],
  [
    {
      pic: "/Images/Avatar.svg",
      name: "Rhiannon Matthaias",
      email: "rhimat@com",
      bookingHistory: 23,
      date: "Oct 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Dain Aetos",
      email: "dainaetos@com",
      bookingHistory: 21,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Garrick Matthews",
      email: "garrick@com",
      bookingHistory: 25,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Mira Sorrengail",
      email: "mirasorren@com",
      bookingHistory: 13,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Ridoc Davis",
      email: "ridocdav@com",
      bookingHistory: 12,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Liam Mairi",
      email: "liammairi@com",
      bookingHistory: 5,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Violet Sorrengail",
      email: "violetdrier@com",
      bookingHistory: 10,
      date: "Sept 24, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
  ],
  [
    {
      pic: "/Images/Avatar.svg",
      name: "Rhiannon Matthaias",
      email: "rhimat@com",
      bookingHistory: 23,
      date: "Oct 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Dain Aetos",
      email: "dainaetos@com",
      bookingHistory: 21,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Garrick Matthews",
      email: "garrick@com",
      bookingHistory: 25,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Mira Sorrengail",
      email: "mirasorren@com",
      bookingHistory: 13,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Ridoc Davis",
      email: "ridocdav@com",
      bookingHistory: 12,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Liam Mairi",
      email: "liammairi@com",
      bookingHistory: 5,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Violet Sorrengail",
      email: "violetdrier@com",
      bookingHistory: 10,
      date: "Sept 24, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
  ],
  [
    {
      pic: "/Images/Avatar.svg",
      name: "Rhiannon Matthaias",
      email: "rhimat@com",
      bookingHistory: 23,
      date: "Oct 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Dain Aetos",
      email: "dainaetos@com",
      bookingHistory: 21,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Garrick Matthews",
      email: "garrick@com",
      bookingHistory: 25,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Mira Sorrengail",
      email: "mirasorren@com",
      bookingHistory: 13,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Ridoc Davis",
      email: "ridocdav@com",
      bookingHistory: 12,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Liam Mairi",
      email: "liammairi@com",
      bookingHistory: 5,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Violet Sorrengail",
      email: "violetdrier@com",
      bookingHistory: 10,
      date: "Sept 24, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
  ],
  [
    {
      pic: "/Images/Avatar.svg",
      name: "Rhiannon Matthaias",
      email: "rhimat@com",
      bookingHistory: 23,
      date: "Oct 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Dain Aetos",
      email: "dainaetos@com",
      bookingHistory: 21,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Garrick Matthews",
      email: "garrick@com",
      bookingHistory: 25,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Mira Sorrengail",
      email: "mirasorren@com",
      bookingHistory: 13,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Ridoc Davis",
      email: "ridocdav@com",
      bookingHistory: 12,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Liam Mairi",
      email: "liammairi@com",
      bookingHistory: 5,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Violet Sorrengail",
      email: "violetdrier@com",
      bookingHistory: 10,
      date: "Sept 24, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
  ],
  [
    {
      pic: "/Images/Avatar.svg",
      name: "Rhiannon Matthaias",
      email: "rhimat@com",
      bookingHistory: 23,
      date: "Oct 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Dain Aetos",
      email: "dainaetos@com",
      bookingHistory: 21,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Garrick Matthews",
      email: "garrick@com",
      bookingHistory: 25,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Mira Sorrengail",
      email: "mirasorren@com",
      bookingHistory: 13,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Ridoc Davis",
      email: "ridocdav@com",
      bookingHistory: 12,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Liam Mairi",
      email: "liammairi@com",
      bookingHistory: 5,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Violet Sorrengail",
      email: "violetdrier@com",
      bookingHistory: 10,
      date: "Sept 24, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
  ],
  [
    {
      pic: "/Images/Avatar.svg",
      name: "Rhiannon Matthaias",
      email: "rhimat@com",
      bookingHistory: 23,
      date: "Oct 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Dain Aetos",
      email: "dainaetos@com",
      bookingHistory: 21,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Garrick Matthews",
      email: "garrick@com",
      bookingHistory: 25,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Mira Sorrengail",
      email: "mirasorren@com",
      bookingHistory: 13,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Ridoc Davis",
      email: "ridocdav@com",
      bookingHistory: 12,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Liam Mairi",
      email: "liammairi@com",
      bookingHistory: 5,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Violet Sorrengail",
      email: "violetdrier@com",
      bookingHistory: 10,
      date: "Sept 24, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
  ],
  [
    {
      pic: "/Images/Avatar.svg",
      name: "Rhiannon Matthaias",
      email: "rhimat@com",
      bookingHistory: 23,
      date: "Oct 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Dain Aetos",
      email: "dainaetos@com",
      bookingHistory: 21,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Garrick Matthews",
      email: "garrick@com",
      bookingHistory: 25,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Mira Sorrengail",
      email: "mirasorren@com",
      bookingHistory: 13,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Ridoc Davis",
      email: "ridocdav@com",
      bookingHistory: 12,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Liam Mairi",
      email: "liammairi@com",
      bookingHistory: 5,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Violet Sorrengail",
      email: "violetdrier@com",
      bookingHistory: 10,
      date: "Sept 24, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
  ],
  [
    {
      pic: "/Images/Avatar.svg",
      name: "Rhiannon Matthaias",
      email: "rhimat@com",
      bookingHistory: 23,
      date: "Oct 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Dain Aetos",
      email: "dainaetos@com",
      bookingHistory: 21,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Garrick Matthews",
      email: "garrick@com",
      bookingHistory: 25,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Mira Sorrengail",
      email: "mirasorren@com",
      bookingHistory: 13,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Ridoc Davis",
      email: "ridocdav@com",
      bookingHistory: 12,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Liam Mairi",
      email: "liammairi@com",
      bookingHistory: 5,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Violet Sorrengail",
      email: "violetdrier@com",
      bookingHistory: 10,
      date: "Sept 24, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
  ],
  [
    {
      pic: "/Images/Avatar.svg",
      name: "Rhiannon Matthaias",
      email: "rhimat@com",
      bookingHistory: 23,
      date: "Oct 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Dain Aetos",
      email: "dainaetos@com",
      bookingHistory: 21,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Garrick Matthews",
      email: "garrick@com",
      bookingHistory: 25,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Mira Sorrengail",
      email: "mirasorren@com",
      bookingHistory: 13,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Ridoc Davis",
      email: "ridocdav@com",
      bookingHistory: 12,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Liam Mairi",
      email: "liammairi@com",
      bookingHistory: 5,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Violet Sorrengail",
      email: "violetdrier@com",
      bookingHistory: 10,
      date: "Sept 24, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
  ],
  [
    {
      pic: "/Images/Avatar.svg",
      name: "Rhiannon Matthaias",
      email: "rhimat@com",
      bookingHistory: 23,
      date: "Oct 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Dain Aetos",
      email: "dainaetos@com",
      bookingHistory: 21,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Garrick Matthews",
      email: "garrick@com",
      bookingHistory: 25,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Mira Sorrengail",
      email: "mirasorren@com",
      bookingHistory: 13,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Ridoc Davis",
      email: "ridocdav@com",
      bookingHistory: 12,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Liam Mairi",
      email: "liammairi@com",
      bookingHistory: 5,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Violet Sorrengail",
      email: "violetdrier@com",
      bookingHistory: 10,
      date: "Sept 24, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
  ],
  [
    {
      pic: "/Images/Avatar.svg",
      name: "Rhiannon Matthaias",
      email: "rhimat@com",
      bookingHistory: 23,
      date: "Oct 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Dain Aetos",
      email: "dainaetos@com",
      bookingHistory: 21,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Garrick Matthews",
      email: "garrick@com",
      bookingHistory: 25,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Mira Sorrengail",
      email: "mirasorren@com",
      bookingHistory: 13,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Ridoc Davis",
      email: "ridocdav@com",
      bookingHistory: 12,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Liam Mairi",
      email: "liammairi@com",
      bookingHistory: 5,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Violet Sorrengail",
      email: "violetdrier@com",
      bookingHistory: 10,
      date: "Sept 24, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
  ],
  [
    {
      pic: "/Images/Avatar.svg",
      name: "Rhiannon Matthaias",
      email: "rhimat@com",
      bookingHistory: 23,
      date: "Oct 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Dain Aetos",
      email: "dainaetos@com",
      bookingHistory: 21,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Garrick Matthews",
      email: "garrick@com",
      bookingHistory: 25,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Suspended",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Mira Sorrengail",
      email: "mirasorren@com",
      bookingHistory: 13,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Ridoc Davis",
      email: "ridocdav@com",
      bookingHistory: 12,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Flagged",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Liam Mairi",
      email: "liammairi@com",
      bookingHistory: 5,
      date: "Jan 16, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
    {
      pic: "/Images/Avatar.svg",
      name: "Violet Sorrengail",
      email: "violetdrier@com",
      bookingHistory: 10,
      date: "Sept 24, 2025",
      purchases: "₦280,000",
      status: "Active",
      menu: "/Icons/Dropdown.svg",
    },
  ],
];
export const experts = [
  {
    icon: "/Icons/user.svg",
    title: "Total Experts",
    menu: "/Icons/Dropdown.svg",
    figure: "2,736",
    img: "/Icons/arrow-up-right.svg",
    per: "100%",
  },
  {
    icon: "/Icons/user.svg",
    title: "Active Experts",
    menu: "/Icons/Dropdown.svg",
    figure: "316",
    img: "/Icons/arrow-up-right.svg",
    per: "100%",
  },
  {
    icon: "/Icons/user.svg",
    title: "Suspended Experts",
    menu: "/Icons/Dropdown.svg",
    figure: "21",
    img: "/Icons/arrow-up-right.svg",
    per: "100%",
  },
];
export const stats = [
  {
    title: "Total Spent",
    value: "₦63,500",
    icon: "/Icons/arrow-down.svg",
    change: "100%",
  },
  {
    title: "Products Purchased",
    value: "12",
    icon: "/Icons/arrow-up.svg",
    change: "100%",
  },
  {
    title: "Workshops Attended",
    value: "5",
    icon: "/Icons/arrow-up.svg",
    change: "100%",
  },
  {
    title: "Sessions Booked",
    value: "3",
    icon: "/Icons/arrow-up.svg",
    change: "100%",
  },
];
export const clientPurchases = [
  {
    title: "Freelance Toolkit",
    type: "Template",
    seller: "@SmartStrategy",
    date: "Apr 12, 2023",
    time: "| 09:32AM",
    price: "₦5,000",
    status: "Delivered",
    action: "View",
    secondActions: "Download",
  },
  {
    title: "Launch Checklist Video",
    type: "Video",
    seller: "@TemplateKing",
    date: "Apr 12, 2023",
    time: "| 09:32AM",
    price: "₦5,000",
    status: "Delivered",
    action: "View",
    secondActions: "Download",
  },
  {
    title: "Branding Guide",
    type: "eBook",
    seller: "@DesignBoss",
    date: "Apr 12, 2023",
    time: "| 09:32AM",
    price: "₦5,000",
    status: "Delivered",
    action: "View",
    secondActions: "Download",
  },
];
export const consultations = [
  {
    title: "Intro to UX",
    type: "@SmartStrategy",
    date: "May 30, 2025 | 09: 32AM",
    price: "₦5,000",
    rating: 4.6,
    status: "Completed",
    action: "View",
    secondActions: "Review",
  },
  {
    title: "Launch Checklist Video",
    type: "@TemplateKing",
    date: "June 5, 2025 | 09: 32AM",
    price: "₦5,000",
    rating: "-",
    status: "Due",
    action: "View",
    secondActions: "Rebook",
  },
  {
    title: "Pricing Masterclass",
    type: "@DesignBoss",
    date: "Apr 12, 2023 | 09: 32AM",
    price: "₦5,000",
    rating: "-",
    status: "Expired",
    action: "View",
    secondActions: "Review",
  },
];
